wandb_version: 1

epochs:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698364434.721254
    t:
      1:
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
    framework: huggingface
