wandb_version: 1

epochs:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698588852.585756
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
